# Generated by Django 3.1.5 on 2021-11-16 22:41

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamiliaProducto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoProducto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ListaPrecio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PedidoVenta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(default=datetime.datetime(2021, 11, 16, 22, 39, 38, 308287, tzinfo=utc))),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('idFamilia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.familiaproducto')),
                ('idGrupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.grupoproducto')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoVentaLinea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=20)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=20)),
                ('moneda', models.CharField(max_length=3)),
                ('idPedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.pedidoventa')),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.producto')),
            ],
        ),
        migrations.AddField(
            model_name='pedidoventa',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.cliente'),
        ),
        migrations.AddField(
            model_name='pedidoventa',
            name='idListaPrecio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.listaprecio'),
        ),
        migrations.CreateModel(
            name='ListaPrecioLinea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=20)),
                ('moneda', models.CharField(max_length=3)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=20)),
                ('fecha_hora', models.DateTimeField(default=datetime.datetime(2021, 11, 16, 22, 39, 38, 306328, tzinfo=utc))),
                ('idListaPrecio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.listaprecio')),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.producto')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='idListaPrecioDefault',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main.listaprecio'),
            preserve_default=False,
        ),
    ]
