# Generated by Django 3.1.5 on 2021-11-16 22:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211116_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantPorBulto',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad',
            field=models.CharField(default='DI', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listapreciolinea',
            name='fecha_hora',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 16, 22, 44, 54, 356968, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pedidoventa',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2021, 11, 16, 22, 44, 54, 358998, tzinfo=utc)),
        ),
    ]
