# Generated by Django 3.1.5 on 2021-11-17 00:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211116_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listapreciolinea',
            name='fecha_hora',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 17, 0, 8, 54, 745903, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pedidoventa',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2021, 11, 17, 0, 8, 54, 747898, tzinfo=utc)),
        ),
    ]
