# Generated by Django 3.1.5 on 2021-11-28 19:45

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211116_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='idListaPrecioDefault',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.listaprecio'),
        ),
        migrations.AlterField(
            model_name='listapreciolinea',
            name='fecha_hora',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 28, 19, 45, 25, 712308, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pedidoventa',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2021, 11, 28, 19, 45, 25, 714342, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='producto',
            name='idFamilia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.familiaproducto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='idGrupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.grupoproducto'),
        ),
    ]
