# Generated by Django 3.1.5 on 2022-05-21 20:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20220521_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listapreciolinea',
            name='fecha_hora',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 21, 20, 24, 50, 424852, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pedidoventa',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2022, 5, 21, 20, 24, 50, 427844, tzinfo=utc)),
        ),
    ]
